"""Unit tests for Badge Service (T054)."""

import pytest
import base64
from PIL import Image
from io import BytesIO
from datetime import datetime

from src.personalization.services.badge_service import (
    BadgeService,
    get_badge_service,
    RARITY_COLORS
)


@pytest.fixture
def badge_service():
    """Create badge service instance."""
    return BadgeService()


@pytest.fixture
def achievement_data():
    """Create sample achievement data."""
    return {
        "id": "ch_1_complete",
        "title": "Chapter 1 Master",
        "description": "Completed Chapter 1",
        "icon": "📚",
        "points": 10,
        "rarity": "common",
        "earned_date": "2026-02-06T10:30:00"
    }


class TestBadgeGeneration:
    """Tests for basic badge generation."""

    def test_generate_badge_returns_bytes(self, badge_service, achievement_data):
        """Test that generate_badge returns bytes by default."""
        result = badge_service.generate_badge(achievement_data, format="bytes")

        assert result is not None
        assert isinstance(result, bytes)
        assert len(result) > 0

    def test_generate_badge_returns_base64(self, badge_service, achievement_data):
        """Test that generate_badge can return base64 string."""
        result = badge_service.generate_badge(achievement_data, format="base64")

        assert result is not None
        assert isinstance(result, str)
        # Base64 strings contain only alphanumeric, +, /, and =
        assert all(c in "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=" for c in result)

    def test_generate_badge_returns_pil_image(self, badge_service, achievement_data):
        """Test that generate_badge can return PIL Image."""
        result = badge_service.generate_badge(achievement_data, format="pil")

        assert result is not None
        assert isinstance(result, Image.Image)
        assert result.size == (300, 300)

    def test_generate_badge_size(self, badge_service, achievement_data):
        """Test that badge has correct dimensions."""
        result = badge_service.generate_badge(achievement_data, format="pil")

        assert result.width == 300
        assert result.height == 300

    def test_generate_badge_png_format(self, badge_service, achievement_data):
        """Test that generated bytes are valid PNG."""
        result = badge_service.generate_badge(achievement_data, format="bytes")

        # PNG files start with these magic bytes
        assert result[:8] == b'\x89PNG\r\n\x1a\n'

    def test_generate_badge_default_format(self, badge_service, achievement_data):
        """Test that default format is bytes."""
        result1 = badge_service.generate_badge(achievement_data)
        result2 = badge_service.generate_badge(achievement_data, format="bytes")

        assert type(result1) == type(result2)
        assert result1 == result2


class TestBadgeRarities:
    """Tests for different rarity levels."""

    def test_generate_badge_common_rarity(self, badge_service):
        """Test badge generation with common rarity."""
        data = {
            "title": "Common Achievement",
            "icon": "⭐",
            "rarity": "common",
            "earned_date": "2026-02-06"
        }
        result = badge_service.generate_badge(data, format="pil")

        assert result is not None
        assert result.size == (300, 300)

    def test_generate_badge_uncommon_rarity(self, badge_service):
        """Test badge generation with uncommon rarity."""
        data = {
            "title": "Uncommon Achievement",
            "icon": "✨",
            "rarity": "uncommon",
            "earned_date": "2026-02-06"
        }
        result = badge_service.generate_badge(data, format="pil")

        assert result is not None

    def test_generate_badge_rare_rarity(self, badge_service):
        """Test badge generation with rare rarity."""
        data = {
            "title": "Rare Achievement",
            "icon": "💎",
            "rarity": "rare",
            "earned_date": "2026-02-06"
        }
        result = badge_service.generate_badge(data, format="pil")

        assert result is not None

    def test_generate_badge_epic_rarity(self, badge_service):
        """Test badge generation with epic rarity."""
        data = {
            "title": "Epic Achievement",
            "icon": "🔥",
            "rarity": "epic",
            "earned_date": "2026-02-06"
        }
        result = badge_service.generate_badge(data, format="pil")

        assert result is not None

    def test_generate_badge_legendary_rarity(self, badge_service):
        """Test badge generation with legendary rarity."""
        data = {
            "title": "Legendary Achievement",
            "icon": "👑",
            "rarity": "legendary",
            "earned_date": "2026-02-06"
        }
        result = badge_service.generate_badge(data, format="pil")

        assert result is not None

    def test_generate_badge_unknown_rarity(self, badge_service):
        """Test badge generation with unknown rarity defaults to common."""
        data = {
            "title": "Unknown Achievement",
            "icon": "🏆",
            "rarity": "unknown",
            "earned_date": "2026-02-06"
        }
        result = badge_service.generate_badge(data, format="pil")

        assert result is not None


class TestBadgeWithPoints:
    """Tests for badges with points display."""

    def test_generate_badge_with_points(self, badge_service, achievement_data):
        """Test badge generation with points."""
        result = badge_service.generate_badge_with_points(achievement_data, format="bytes")

        assert result is not None
        assert isinstance(result, bytes)
        assert len(result) > 0

    def test_generate_badge_with_points_returns_pil(self, badge_service, achievement_data):
        """Test that generate_badge_with_points can return PIL Image."""
        result = badge_service.generate_badge_with_points(achievement_data, format="pil")

        assert result is not None
        assert isinstance(result, Image.Image)
        assert result.size == (300, 300)

    def test_generate_badge_with_points_various_values(self, badge_service):
        """Test badge with different point values."""
        for points in [0, 5, 10, 25, 50, 100]:
            data = {
                "title": "Test Achievement",
                "icon": "🏆",
                "points": points,
                "rarity": "common",
                "earned_date": "2026-02-06"
            }
            result = badge_service.generate_badge_with_points(data, format="pil")

            assert result is not None


class TestBadgeFormatConversion:
    """Tests for format conversion methods."""

    def test_base64_roundtrip(self, badge_service, achievement_data):
        """Test that base64 string can be converted back to image."""
        # Generate badge as base64
        base64_str = badge_service.generate_badge(achievement_data, format="base64")

        # Decode and verify it's a valid image
        img_bytes = base64.b64decode(base64_str)
        img = Image.open(BytesIO(img_bytes))

        assert img is not None
        assert img.size == (300, 300)

    def test_bytes_to_pil_conversion(self, badge_service, achievement_data):
        """Test that bytes can be converted to PIL Image."""
        # Generate badge as bytes
        img_bytes = badge_service.generate_badge(achievement_data, format="bytes")

        # Convert to PIL Image
        img = Image.open(BytesIO(img_bytes))

        assert img is not None
        assert img.size == (300, 300)
        assert img.format == "PNG"


class TestBadgeDataHandling:
    """Tests for handling various achievement data."""

    def test_generate_badge_missing_title(self, badge_service):
        """Test badge generation with missing title."""
        data = {
            "icon": "🏆",
            "rarity": "common",
            "earned_date": "2026-02-06"
        }
        result = badge_service.generate_badge(data, format="bytes")

        assert result is not None

    def test_generate_badge_missing_icon(self, badge_service):
        """Test badge generation with missing icon."""
        data = {
            "title": "Achievement",
            "rarity": "common",
            "earned_date": "2026-02-06"
        }
        result = badge_service.generate_badge(data, format="bytes")

        assert result is not None

    def test_generate_badge_missing_earned_date(self, badge_service):
        """Test badge generation with missing earned date."""
        data = {
            "title": "Achievement",
            "icon": "🏆",
            "rarity": "common"
        }
        result = badge_service.generate_badge(data, format="bytes")

        assert result is not None

    def test_generate_badge_long_title(self, badge_service):
        """Test badge generation with very long title."""
        data = {
            "title": "This is a very long achievement title that should be wrapped across multiple lines",
            "icon": "🏆",
            "rarity": "common",
            "earned_date": "2026-02-06"
        }
        result = badge_service.generate_badge(data, format="pil")

        assert result is not None
        assert result.size == (300, 300)

    def test_generate_badge_with_emoji_title(self, badge_service):
        """Test badge generation with emoji in title."""
        data = {
            "title": "🏆 Epic Victory 🏆",
            "icon": "🎉",
            "rarity": "epic",
            "earned_date": "2026-02-06"
        }
        result = badge_service.generate_badge(data, format="bytes")

        assert result is not None


class TestBadgeEdgeCases:
    """Tests for edge cases and error handling."""

    def test_generate_badge_empty_achievement(self, badge_service):
        """Test badge generation with empty achievement data."""
        result = badge_service.generate_badge({}, format="bytes")

        assert result is not None

    def test_generate_badge_none_rarity(self, badge_service):
        """Test badge generation with None rarity."""
        data = {
            "title": "Achievement",
            "icon": "🏆",
            "rarity": None,
            "earned_date": "2026-02-06"
        }
        result = badge_service.generate_badge(data, format="bytes")

        assert result is not None

    def test_generate_badge_zero_points(self, badge_service):
        """Test badge with zero points."""
        data = {
            "title": "No Points Achievement",
            "icon": "🏆",
            "points": 0,
            "rarity": "common",
            "earned_date": "2026-02-06"
        }
        result = badge_service.generate_badge_with_points(data, format="bytes")

        assert result is not None


class TestBadgeServiceFactory:
    """Tests for factory function."""

    @pytest.mark.asyncio
    async def test_get_badge_service(self):
        """Test factory function creates service correctly."""
        service = await get_badge_service()

        assert isinstance(service, BadgeService)
        assert service.badge_width == 300
        assert service.badge_height == 300


class TestRarityColors:
    """Tests for rarity color configuration."""

    def test_rarity_colors_complete(self):
        """Test that all rarity colors are defined."""
        expected_rarities = ["common", "uncommon", "rare", "epic", "legendary"]

        for rarity in expected_rarities:
            assert rarity in RARITY_COLORS

    def test_rarity_colors_structure(self):
        """Test that rarity colors have correct structure."""
        required_fields = ["bg", "border", "text"]

        for rarity, colors in RARITY_COLORS.items():
            for field in required_fields:
                assert field in colors
                # Verify it's a valid hex color
                assert colors[field].startswith("#")
                assert len(colors[field]) == 7  # #RRGGBB format
